project_id = "bizhrhajcvpipxcmoysj"

[functions.parse-document]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true

[functions.generate-flashcards]
verify_jwt = true

[functions.generate-notifications]
verify_jwt = false